export default [
    { id: 'AirPassengers', label: `Monthly Airline Passenger Numbers 1949-1960` },
    { id: 'BJsales', label: `Sales Data with Leading Indicator` },
    { id: 'BOD', label: `Biochemical Oxygen Demand` },
    { id: 'Formaldehyde', label: `Determination of Formaldehyde` },
    { id: 'HairEyeColor', label: `Hair and Eye Color of Statistics Students` },
    { id: 'InsectSprays', label: `Effectiveness of Insect Sprays` },
    { id: 'JohnsonJohnson', label: `Quarterly Earnings per Johnson & Johnson Share` },
    { id: 'LakeHuron', label: `Level of Lake Huron 1875-1972` },
    { id: 'LifeCycleSavings', label: `Intercountry Life-Cycle Savings Data` },
    { id: 'Nile', label: `Flow of the River Nile` },
    { id: 'OrchardSprays', label: `Potency of Orchard Sprays` },
    { id: 'PlantGrowth', label: `Results from an Experiment on Plant Growth` },
    { id: 'Puromycin', label: `Reaction Velocity of an Enzymatic Reaction` },
    { id: 'Titanic', label: `Survival of passengers on the Titanic` },
    { id: 'ToothGrowth', label: `The Effect of Vitamin C on Tooth Growth in Guinea Pigs` },
    { id: 'UCBAdmissions', label: `Student Admissions at UC Berkeley` },
    { id: 'UKDriverDeaths', label: `Road Casualties in Great Britain 1969-84` },
    { id: 'UKgas', label: `UK Quarterly Gas Consumption` },
    { id: 'USAccDeaths', label: `Accidental Deaths in the US 1973-1978` },
    { id: 'USArrests', label: `Violent Crime Rates by US State` },
    { id: 'USJudgeRatings', label: `Lawyers' Ratings of State Judges in the US Superior Court` },
    { id: 'USPersonalExpenditure', label: `Personal Expenditure Data` },
    { id: 'VADeaths', label: `Death Rates in Virginia (1940)` },
    { id: 'WWWusage', label: `Internet Usage per Minute` },
    { id: 'WorldPhones', label: `The World's Telephones` },
    { id: 'airmiles', label: `Passenger Miles on Commercial US Airlines, 1937-1960` },
    { id: 'airquality', label: `New York Air Quality Measurements` },
    { id: 'anscombe', label: `Anscombe's Quartet of 'Identical' Simple Linear Regressions` },
    { id: 'attenu', label: `The Joyner-Boore Attenuation Data` },
    { id: 'attitude', label: `The Chatterjee-Price Attitude Data` },
    { id: 'austres', label: `Quarterly Time Series of the Number of Australian Residents` },
    { id: 'cars', label: `Speed and Stopping Distances of Cars` },
    { id: 'chickwts', label: `Chicken Weights by Feed Type` },
    { id: 'co2', label: `Mauna Loa Atmospheric CO2 Concentration` },
    { id: 'crimtab', label: `Student's 3000 Criminals Data` },
    { id: 'discoveries', label: `Yearly Numbers of Important Discoveries` },
    { id: 'esoph', label: `Smoking, Alcohol and (O)esophageal Cancer` },
    { id: 'euro', label: `Conversion Rates of Euro Currencies` },
    { id: 'faithful', label: `Old Faithful Geyser Data` },
    { id: 'freeny', label: `Freeny's Revenue Data` },
    { id: 'infert', label: `Infertility after Spontaneous and Induced Abortion` },
    { id: 'iris', label: `Edgar Anderson's Iris Data` },
    { id: 'islands', label: `Areas of the World's Major Landmasses` },
    { id: 'lh', label: `Luteinizing Hormone in Blood Samples` },
    { id: 'longley', label: `Longley's Economic Regression Data` },
    { id: 'lynx', label: `Annual Canadian Lynx trappings 1821-1934` },
    { id: 'morley', label: `Michelson Speed of Light Data` },
    { id: 'mtcars', label: `Motor Trend Car Road Tests` },
    { id: 'nhtemp', label: `Average Yearly Temperatures in New Haven` },
    { id: 'nottem', label: `Average Monthly Temperatures at Nottingham, 1920-1939` },
    { id: 'npk', label: `Classical N, P, K Factorial Experiment` },
    { id: 'occupationalStatus', label: `Occupational Status of Fathers and their Sons` },
    { id: 'precip', label: `Annual Precipitation in US Cities` },
    { id: 'presidents', label: `Quarterly Approval Ratings of US Presidents` },
    { id: 'pressure', label: `Vapor Pressure of Mercury as a Function of Temperature` },
    { id: 'quakes', label: `Locations of Earthquakes off Fiji` },
    { id: 'randu', label: `Random Numbers from Congruential Generator RANDU` },
    { id: 'rivers', label: `Lengths of Major North American Rivers` },
    { id: 'rock', label: `Measurements on Petroleum Rock Samples` },
    { id: 'sleep', label: `Student's Sleep Data` },
    { id: 'stackloss', label: `Brownlee's Stack Loss Plant Data` },
    { id: 'sunspot.month', label: `Monthly Sunspot Data, from 1749 to ""Present""` },
    { id: 'sunspot.year', label: `Yearly Sunspot Data, 1700-1988` },
    { id: 'sunspots', label: `Monthly Sunspot Numbers, 1749-1983` },
    { id: 'swiss', label: `Swiss Fertility and Socioeconomic Indicators (1888) Data` },
    { id: 'treering', label: `Yearly Treering Data, -6000-1979` },
    { id: 'trees', label: `Girth, Height and Volume for Black Cherry Trees` },
    { id: 'uspop', label: `Populations Recorded by the US Census` },
    { id: 'volcano', label: `Topographic Information on Auckland's Maunga Whau Volcano` },
    { id: 'warpbreaks', label: `The Number of Breaks in Yarn during Weaving` },
    { id: 'women', label: `Average Heights and Weights for American Women` },
    { id: 'acme', label: `Monthly Excess Returns` },
    { id: 'aids', label: `Delay in AIDS Reporting in England and Wales` },
    { id: 'aircondit', label: `Failures of Air-conditioning Equipment` },
    { id: 'aircondit7', label: `Failures of Air-conditioning Equipment` },
    { id: 'amis', label: `Car Speeding and Warning Signs` },
    { id: 'aml', label: `Remission Times for Acute Myelogenous Leukaemia` },
    { id: 'bigcity', label: `Population of U.S. Cities` },
    { id: 'brambles', label: `Spatial Location of Bramble Canes` },
    { id: 'breslow', label: `Smoking Deaths Among Doctors` },
    { id: 'calcium', label: `Calcium Uptake Data` },
    { id: 'cane', label: `Sugar-cane Disease Data` },
    { id: 'capability', label: `Simulated Manufacturing Process Data` },
    { id: 'catsM', label: `Weight Data for Domestic Cats` },
    { id: 'cav', label: `Position of Muscle Caveolae` },
    { id: 'cd4', label: `CD4 Counts for HIV-Positive Patients` },
    { id: 'channing', label: `Channing House Data` },
    { id: 'city', label: `Population of U.S. Cities` },
    { id: 'claridge', label: `Genetic Links to Left-handedness` },
    { id: 'cloth', label: `Number of Flaws in Cloth` },
    { id: 'co.transfer', label: `Carbon Monoxide Transfer` },
    { id: 'coal', label: `Dates of Coal Mining Disasters` },
    { id: 'darwin', label: `Darwin's Plant Height Differences` },
    { id: 'dogs', label: `Cardiac Data for Domestic Dogs` },
    { id: 'downs.bc', label: `Incidence of Down's Syndrome in British Columbia` },
    { id: 'ducks', label: `Behavioral and Plumage Characteristics of Hybrid Ducks` },
    { id: 'fir', label: `Counts of Balsam-fir Seedlings` },
    { id: 'frets', label: `Head Dimensions in Brothers` },
    { id: 'grav', label: `Acceleration Due to Gravity` },
    { id: 'gravity', label: `Acceleration Due to Gravity` },
    { id: 'hirose', label: `Failure Time of PET Film` },
    { id: 'islay', label: `Jura Quartzite Azimuths on Islay` },
    { id: 'manaus', label: `Average Heights of the Rio Negro river at Manaus` },
    { id: 'melanoma', label: `Survival from Malignant Melanoma` },
    { id: 'motor', label: `Data from a Simulated Motorcycle Accident` },
    { id: 'neuro', label: `Neurophysiological Point Process Data` },
    { id: 'nitrofen', label: `Toxicity of Nitrofen in Aquatic Systems` },
    { id: 'nodal', label: `Nodal Involvement in Prostate Cancer` },
    { id: 'nuclear', label: `Nuclear Power Station Construction Data` },
    { id: 'paulsen', label: `Neurotransmission in Guinea Pig Brains` },
    { id: 'poisons', label: `Animal Survival Times` },
    { id: 'polar', label: `Pole Positions of New Caledonian Laterites` },
    { id: 'remission', label: `Cancer Remission and Cell Activity` },
    { id: 'salinity', label: `Water Salinity and River Discharge` },
    { id: 'survival', label: `Survival of Rats after Radiation Doses` },
    { id: 'tau', label: `Tau Particle Decay Modes` },
    { id: 'tuna', label: `Tuna Sighting Data` },
    { id: 'urine', label: `Urine Analysis Data` },
    { id: 'wool', label: `Australian Relative Wool Prices` },
    { id: 'aids', label: `data from Section 1.19` },
    { id: 'alloauto', label: `data from Section 1.9` },
    { id: 'allograft', label: `data from Exercise 13.1, p418` },
    { id: 'azt', label: `data from Exercise 4.7, p122` },
    { id: 'baboon', label: `data from Exercise 5.8, p147` },
    { id: 'bcdeter', label: `data from Section 1.18` },
    { id: 'bfeed', label: `data from Section 1.14` },
    { id: 'bmt', label: `data from Section 1.3` },
    { id: 'bnct', label: `data from Exercise 7.7, p223` },
    { id: 'btrial', label: `data from Section 1.5` },
    { id: 'burn', label: `data from Section 1.6` },
    { id: 'channing', label: `data from Section 1.16` },
    { id: 'drug6mp', label: `data from Section 1.2` },
    { id: 'drughiv', label: `data from Exercise 7.6, p222` },
    { id: 'hodg', label: `data from Section 1.10` },
    { id: 'kidney', label: `data from Section 1.4` },
    { id: 'kidrecurr', label: `Data on 38 individuals using a kidney dialysis machine` },
    { id: 'kidtran', label: `data from Section 1.7` },
    { id: 'larynx', label: `data from Section 1.8` },
    { id: 'lung', label: `data from Exercise 4.4, p120` },
    { id: 'pneumon', label: `data from Section 1.13` },
    { id: 'psych', label: `data from Section 1.15` },
    { id: 'rats', label: `data from Exercise 7.13, p225` },
    { id: 'std', label: `data from Section 1.12` },
    { id: 'stddiag', label: `data from Exercise 5.6, p146` },
    { id: 'tongue', label: `data from Section 1.11` },
    { id: 'twins', label: `data from Exercise 7.14, p225` },
    { id: 'Animals2', label: `Brain and Body Weights for 65 Species of Land Animals` },
    { id: 'CrohnD', label: `Crohn's Disease Adverse Events Data` },
    { id: 'NOxEmissions', label: `NOx Air Pollution Data` },
    { id: 'SiegelsEx', label: `Siegel's Exact Fit Example Data` },
    { id: 'aircraft', label: `Aircraft Data` },
    { id: 'airmay', label: `Air Quality Data` },
    { id: 'alcohol', label: `Alcohol Solubility in Water Data` },
    { id: 'ambientNOxCH', label: `Daily Means of NOx (mono-nitrogen oxides) in air` },
    { id: 'bushfire', label: `Campbell Bushfire Data` },
    { id: 'carrots', label: `Insect Damages on Carrots` },
    { id: 'cloud', label: `Cloud point of a Liquid` },
    { id: 'coleman', label: `Coleman Data Set` },
    { id: 'condroz', label: `Condroz Data` },
    { id: 'cushny', label: `Cushny and Peebles Prolongation of Sleep Data` },
    { id: 'delivery', label: `Delivery Time Data` },
    { id: 'education', label: `Education Expenditure Data` },
    { id: 'epilepsy', label: `Epilepsy Attacks Data Set` },
    { id: 'exAM', label: `Example Data of Antille and May - for Simple Regression` },
    { id: 'foodstamp', label: `Food Stamp Program Participation` },
    { id: 'hbk', label: `Hawkins, Bradu, Kass's Artificial Data` },
    { id: 'heart', label: `Heart Catherization Data` },
    { id: 'kootenay', label: `Waterflow Measurements of Kootenay River in Libby and Newgate` },
    { id: 'lactic', label: `Lactic Acid Concentration Measurement Data` },
    { id: 'milk', label: `Daudin's Milk Composition Data` },
    { id: 'pension', label: `Pension Funds Data` },
    { id: 'phosphor', label: `Phosphorus Content Data` },
    { id: 'pilot', label: `Pilot-Plant Data` },
    { id: 'possumDiv', label: `Possum Diversity Data` },
    { id: 'pulpfiber', label: `Pulp Fiber and Paper Data` },
    { id: 'radarImage', label: `Satellite Radar Image Data from near Munich` },
    { id: 'salinity', label: `Salinity Data` },
    { id: 'starsCYG', label: `Hertzsprung-Russell Diagram Data of Star Cluster CYG OB1` },
    { id: 'telef', label: `Number of International Calls from Belgium` },
    { id: 'toxicity', label: `Toxicity of Carboxylic Acids Data` },
    { id: 'vaso', label: `Vaso Constriction Skin Data Set` },
    { id: 'wagnerGrowth', label: `Wagner's Hannover Employment Growth Data` },
    { id: 'wood', label: `Modified Data on Wood Specific Gravity` },
    { id: 'AMSsurvey', label: `American Math Society Survey Data` },
    { id: 'Adler', label: `Experimenter Expectations` },
    { id: 'Angell', label: `Moral Integration of American Cities` },
    { id: 'Anscombe', label: `U. S. State Public-School Expenditures` },
    { id: 'Baumann', label: `Methods of Teaching Reading Comprehension` },
    { id: 'Bfox', label: `Canadian Women's Labour-Force Participation` },
    { id: 'Blackmoor', label: `Exercise Histories of Eating-Disordered and Control Subjects` },
    { id: 'Burt', label: `Fraudulent Data on IQs of Twins Raised Apart` },
    { id: 'CanPop', label: `Canadian Population Data` },
    { id: 'Chile', label: `Voting Intentions in the 1988 Chilean Plebiscite` },
    { id: 'Chirot', label: `The 1907 Romanian Peasant Rebellion` },
    { id: 'Cowles', label: `Cowles and Davis's Data on Volunteering` },
    { id: 'Davis', label: `Self-Reports of Height and Weight` },
    { id: 'DavisThin', label: `Davis's Data on Drive for Thinness` },
    { id: 'Depredations', label: `Minnesota Wolf Depredation Data` },
    { id: 'Duncan', label: `Duncan's Occupational Prestige Data` },
    { id: 'Ericksen', label: `The 1980 U.S. Census Undercount` },
    { id: 'Florida', label: `Florida County Voting` },
    { id: 'Freedman', label: `Crowding and Crime in U. S. Metropolitan Areas` },
    { id: 'Friendly', label: `Format Effects on Recall` },
    { id: 'Ginzberg', label: `Data on Depression` },
    { id: 'Greene', label: `Refugee Appeals` },
    { id: 'Guyer', label: `Anonymity and Cooperation` },
    { id: 'Hartnagel', label: `Canadian Crime-Rates Time Series` },
    { id: 'Highway1', label: `Highway Accidents` },
    { id: 'Leinhardt', label: `Data on Infant-Mortality` },
    { id: 'Mandel', label: `Contrived Collinear Data` },
    { id: 'Migration', label: `Canadian Interprovincial Migration Data` },
    { id: 'Moore', label: `Status, Authoritarianism, and Conformity` },
    { id: 'Mroz', label: `U.S. Women's Labor-Force Participation` },
    { id: 'OBrienKaiser', label: `O'Brien and Kaiser's Repeated-Measures Data` },
    { id: 'Ornstein', label: `Interlocking Directorates Among Major Canadian Firms` },
    { id: 'Pottery', label: `Chemical Composition of Pottery` },
    { id: 'Prestige', label: `Prestige of Canadian Occupations` },
    { id: 'Quartet', label: `Four Regression Datasets` },
    { id: 'Robey', label: `Fertility and Contraception` },
    { id: 'SLID', label: `Survey of Labour and Income Dynamics` },
    { id: 'Sahlins', label: `Agricultural Production in Mazulu Village` },
    { id: 'Salaries', label: `Salaries for Professors` },
    { id: 'Soils', label: `Soil Compositions of Physical and Chemical Characteristics` },
    { id: 'States', label: `Education and Related Statistics for the U.S. States` },
    { id: 'Transact', label: `Transaction data` },
    { id: 'UN', label: `GDP and Infant Mortality` },
    { id: 'USPop', label: `Population of the United States` },
    { id: 'Vocab', label: `Vocabulary and Education` },
    { id: 'WeightLoss', label: `Weight Loss Data` },
    { id: 'Womenlf', label: `Canadian Women's Labour-Force Participation` },
    { id: 'Wool', label: `Wool data` },
    { id: 'agriculture', label: `European Union Agricultural Workforces` },
    { id: 'animals', label: `Attributes of Animals` },
    { id: 'chorSub', label: `Subset of C-horizon of Kola Data` },
    { id: 'flower', label: `Flower Characteristics` },
    { id: 'plantTraits', label: `Plant Species Traits Data` },
    { id: 'pluton', label: `Isotopic Composition Plutonium Batches` },
    { id: 'ruspini', label: `Ruspini Data` },
    { id: 'votes.repub', label: `Votes for Republican Candidate in Presidential Elections` },
    { id: 'xclara', label: `Bivariate Data Set with 3 Clusters` },
    { id: 'affairs', label: `affairs` },
    { id: 'azcabgptca', label: `azcabgptca` },
    { id: 'azdrg112', label: `azdrg112` },
    { id: 'azpro', label: `azpro` },
    { id: 'azprocedure', label: `azprocedure` },
    { id: 'badhealth', label: `badhealth` },
    { id: 'fasttrakg', label: `fasttrakg` },
    { id: 'fishing', label: `fishing` },
    { id: 'lbw', label: `lbw` },
    { id: 'lbwgrp', label: `lbwgrp` },
    { id: 'loomis', label: `loomis` },
    { id: 'mdvis', label: `mdvis` },
    { id: 'medpar', label: `medpar` },
    { id: 'nuts', label: `nuts` },
    { id: 'rwm', label: `rwm` },
    { id: 'rwm1984', label: `rwm1984` },
    { id: 'rwm5yr', label: `rwm5yr` },
    { id: 'ships', label: `ships` },
    { id: 'smoking', label: `smoking` },
    { id: 'titanic', label: `titanic` },
    { id: 'titanicgrp', label: `titanicgrp` },
    { id: 'Accident', label: `Ship Accidents` },
    { id: 'Airline', label: `Cost for U.S. Airlines` },
    { id: 'Airq', label: `Air Quality for Californian Metropolitan Areas` },
    { id: 'Benefits', label: `Unemployement of Blue Collar Workers` },
    { id: 'Bids', label: `Bids Received By U.S. Firms` },
    { id: 'BudgetFood', label: `Budget Share of Food for Spanish Households` },
    { id: 'BudgetItaly', label: `Budget Shares for Italian Households` },
    { id: 'BudgetUK', label: `Budget Shares of British Households` },
    { id: 'Bwages', label: `Wages in Belgium` },
    { id: 'CPSch3', label: `Earnings from the Current Population Survey` },
    { id: 'CRANpackages', label: `Growth of CRAN` },
    { id: 'Capm', label: `Stock Market Data` },
    { id: 'Car', label: `Stated Preferences for Car Choice` },
    { id: 'Caschool', label: `The California Test Score Data Set` },
    { id: 'Catsup', label: `Choice of Brand for Catsup` },
    { id: 'Cigar', label: `Cigarette Consumption` },
    { id: 'Cigarette', label: `The Cigarette Consumption Panel Data Set` },
    { id: 'Clothing', label: `Sales Data of Men's Fashion Stores` },
    { id: 'Computers', label: `Prices of Personal Computers` },
    { id: 'Cracker', label: `Choice of Brand for Crakers` },
    { id: 'Crime', label: `Crime in North Carolina` },
    { id: 'DM', label: `DM Dollar Exchange Rate` },
    { id: 'Diamond', label: `Pricing the C's of Diamond Stones` },
    { id: 'Doctor', label: `Number of Doctor Visits` },
    { id: 'DoctorAUS', label: `Doctor Visits in Australia` },
    { id: 'DoctorContacts', label: `Contacts With Medical Doctor` },
    { id: 'Earnings', label: `Earnings for Three Age Groups` },
    { id: 'Electricity', label: `Cost Function for Electricity Producers` },
    { id: 'Fair', label: `Extramarital Affairs Data` },
    { id: 'Fatality', label: `Drunk Driving Laws and Traffic Deaths` },
    { id: 'Fishing', label: `Choice of Fishing Mode` },
    { id: 'Forward', label: `Exchange Rates of US Dollar Against Other Currencies` },
    { id: 'FriendFoe', label: `Data from the Television Game Show Friend Or Foe ?` },
    { id: 'Garch', label: `Daily Observations on Exchange Rates of the US Dollar Against Other Currencies` },
    { id: 'Gasoline', label: `Gasoline Consumption` },
    { id: 'Griliches', label: `Wage Datas` },
    { id: 'Grunfeld', label: `Grunfeld Investment Data` },
    { id: 'HC', label: `Heating and Cooling System Choice in Newly Built Houses in California` },
    { id: 'HI', label: `Health Insurance and Hours Worked By Wives` },
    { id: 'Hdma', label: `The Boston HDMA Data Set` },
    { id: 'Heating', label: `Heating System Choice in California Houses` },
    { id: 'Hedonic', label: `Hedonic Prices of Cencus Tracts in Boston` },
    { id: 'Housing', label: `Sales Prices of Houses in the City of Windsor` },
    { id: 'Icecream', label: `Ice Cream Consumption` },
    { id: 'Journals', label: `Economic Journals Dat Set` },
    { id: 'Kakadu', label: `Willingness to Pay for the Preservation of the Kakadu National Park` },
    { id: 'Ketchup', label: `Choice of Brand for Ketchup` },
    { id: 'Klein', label: `Klein's Model I` },
    { id: 'LaborSupply', label: `Wages and Hours Worked` },
    { id: 'Labour', label: `Belgian Firms` },
    { id: 'MCAS', label: `The Massashusets Test Score Data Set` },
    { id: 'Males', label: `Wages and Education of Young Males` },
    { id: 'Mathlevel', label: `Level of Calculus Attained for Students Taking Advanced Micro-economics` },
    { id: 'MedExp', label: `Structure of Demand for Medical Care` },
    { id: 'Metal', label: `Production for SIC 33` },
    { id: 'Mode', label: `Mode Choice` },
    { id: 'ModeChoice', label: `Data to Study Travel Mode Choice` },
    { id: 'Mofa', label: `International Expansion of U.S. Mofa's (majority-owned Foreign Affiliates in Fire (finance, Insurance and Real Estate)` },
    { id: 'Mroz', label: `Labor Supply Data` },
    { id: 'MunExp', label: `Municipal Expenditure Data` },
    { id: 'NaturalPark', label: `Willingness to Pay for the Preservation of the Alentejo Natural Park` },
    { id: 'Nerlove', label: `Cost Function for Electricity Producers, 1955` },
    { id: 'OFP', label: `Visits to Physician Office` },
    { id: 'Oil', label: `Oil Investment` },
    { id: 'PSID', label: `Panel Survey of Income Dynamics` },
    { id: 'Participation', label: `Labor Force Participation` },
    { id: 'PatentsHGH', label: `Dynamic Relation Between Patents and R&D` },
    { id: 'PatentsRD', label: `Patents, R&D and Technological Spillovers for a Panel of Firms` },
    { id: 'Pound', label: `Pound-dollar Exchange Rate` },
    { id: 'Produc', label: `Us States Production` },
    { id: 'RetSchool', label: `Return to Schooling` },
    { id: 'SP500', label: `Returns on Standard & Poor's 500 Index` },
    { id: 'Schooling', label: `Wages and Schooling` },
    { id: 'Somerville', label: `Visits to Lake Somerville` },
    { id: 'Star', label: `Effects on Learning of Small Class Sizes` },
    { id: 'Strike', label: `Strike Duration Data` },
    { id: 'StrikeDur', label: `Strikes Duration` },
    { id: 'StrikeNb', label: `Number of Strikes in Us Manufacturing` },
    { id: 'SumHes', label: `The Penn Table` },
    { id: 'Tobacco', label: `Households Tobacco Budget Share` },
    { id: 'Train', label: `Stated Preferences for Train Traveling` },
    { id: 'TranspEq', label: `Statewide Data on Transportation Equipment Manufacturing` },
    { id: 'Treatment', label: `Evaluating Treatment Effect of Training on Earnings` },
    { id: 'Tuna', label: `Choice of Brand for Tuna` },
    { id: 'USFinanceIndustry', label: `US Finance Industry Profits` },
    { id: 'USclassifiedDocuments', label: `Official Secrecy of the United States Government` },
    { id: 'USstateAbbreviations', label: `Standard abbreviations for states of the United States` },
    { id: 'UStaxWords', label: `Number of Words in US Tax Law` },
    { id: 'UnempDur', label: `Unemployment Duration` },
    { id: 'Unemployment', label: `Unemployment Duration` },
    { id: 'University', label: `Provision of University Teaching and Research` },
    { id: 'VietNamH', label: `Medical Expenses in Viet-nam (household Level)` },
    { id: 'VietNamI', label: `Medical Expenses in Viet-nam (individual Level)` },
    { id: 'Wages', label: `Panel Datas of Individual Wages` },
    { id: 'Wages1', label: `Wages, Experience and Schooling` },
    { id: 'Workinghours', label: `Wife Working Hours` },
    { id: 'Yen', label: `Yen-dollar Exchange Rate` },
    { id: 'Yogurt', label: `Choice of Brand for Yogurts` },
    { id: 'bankingCrises', label: `Countries in Banking Crises` },
    { id: 'incomeInequality', label: `Income Inequality in the US` },
    { id: 'nonEnglishNames', label: `Names with Character Set Problems` },
    { id: 'politicalKnowledge', label: `Political knowledge in the US and Europe` },
    { id: 'PD', label: `A study of Parkinson's disease and APOE, LRRK2, SNCA makers` },
    { id: 'aldh2', label: `ALDH2 markers and Alcoholism` },
    { id: 'apoeapoc', label: `APOE/APOC1 markers and Alzheimer's` },
    { id: 'cf', label: `Cystic fibrosis data` },
    { id: 'crohn', label: `Crohn's disease data` },
    { id: 'fa', label: `Friedreich Ataxia data` },
    { id: 'fsnps', label: `A case-control data involving four SNPs with missing genotype` },
    { id: 'hla', label: `The HLA data` },
    { id: 'hr1420', label: `An example data for Manhattan plot with annotation` },
    { id: 'l51', label: `An example pedigree data` },
    { id: 'lukas', label: `An example pedigree` },
    { id: 'mao', label: `A study of Parkinson's disease and MAO gene` },
    { id: 'mfblong', label: `Example data for ACEnucfam` },
    { id: 'mhtdata', label: `An example data for Manhattan plot` },
    { id: 'nep499', label: `A study of Alzheimer's disease with eight SNPs and APOE` },
    { id: 'diamonds', label: `Prices of 50,000 round cut diamonds` },
    { id: 'economics', label: `US economic time series.` },
    { id: 'midwest', label: `Midwest demographics.` },
    { id: 'movies', label: `Movie information and user ratings from IMDB.com.` },
    { id: 'mpg', label: `Fuel economy data from 1999 and 2008 for 38 popular models of car` },
    { id: 'msleep', label: `An updated and expanded version of the mammals sleep dataset.` },
    { id: 'presidential', label: `Terms of 10 presidents from Eisenhower to Bush W.` },
    { id: 'seals', label: `Vector field of seal movements.` },
    { id: 'Arbuthnot', label: `Arbuthnot's data on male and female birth ratios in London from 1629-1710.` },
    { id: 'Bowley', label: `Bowley's data on values of British and Irish trade, 1855-1899` },
    { id: 'Cavendish', label: `Cavendish's Determinations of the Density of the Earth` },
    { id: 'ChestSizes', label: `Chest measurements of 5738 Scottish Militiamen` },
    { id: 'CushnyPeebles', label: `Cushny-Peebles Data: Soporific Effects of Scopolamine Derivatives` },
    { id: 'CushnyPeeblesN', label: `Cushny-Peebles Data: Soporific Effects of Scopolamine Derivatives` },
    { id: 'Dactyl', label: `Edgeworth's counts of dactyls in Virgil's Aeneid` },
    { id: 'DrinksWages', label: `Elderton and Pearson's (1910) data on drinking and wages` },
    { id: 'Fingerprints', label: `Waite's data on Patterns in Fingerprints` },
    { id: 'Galton', label: `Galton's data on the heights of parents and their children` },
    { id: 'GaltonFamilies', label: `Galton's data on the heights of parents and their children, by child` },
    { id: 'Guerry', label: `Data from A.-M. Guerry, ""Essay on the Moral Statistics of France""` },
    { id: 'Jevons', label: `W. Stanley Jevons' data on numerical discrimination` },
    { id: 'Langren.all', label: `van Langren's Data on Longitude Distance between Toledo and Rome` },
    { id: 'Langren1644', label: `van Langren's Data on Longitude Distance between Toledo and Rome` },
    { id: 'Macdonell', label: `Macdonell's Data on Height and Finger Length of Criminals, used by Gosset (1908)` },
    { id: 'MacdonellDF', label: `Macdonell's Data on Height and Finger Length of Criminals, used by Gosset (1908)` },
    { id: 'Michelson', label: `Michelson's Determinations of the Velocity of Light` },
    { id: 'MichelsonSets', label: `Michelson's Determinations of the Velocity of Light` },
    { id: 'Minard.cities', label: `Data from Minard's famous graphic map of Napoleon's march on Moscow` },
    { id: 'Minard.temp', label: `Data from Minard's famous graphic map of Napoleon's march on Moscow` },
    { id: 'Minard.troops', label: `Data from Minard's famous graphic map of Napoleon's march on Moscow` },
    { id: 'Nightingale', label: `Florence Nightingale's data on deaths from various causes in the Crimean War` },
    { id: 'OldMaps', label: `Latitudes and Longitudes of 39 Points in 11 Old Maps` },
    { id: 'PearsonLee', label: `Pearson and Lee's data on the heights of parents and children classified by gender` },
    { id: 'PolioTrials', label: `Polio Field Trials Data` },
    { id: 'Prostitutes', label: `Parent-Duchatelet's time-series data on the number of prostitutes in Paris` },
    { id: 'Pyx', label: `Trial of the Pyx` },
    { id: 'Quarrels', label: `Statistics of Deadly Quarrels` },
    { id: 'Snow.deaths', label: `John Snow's map and data on the 1854 London Cholera outbreak` },
    { id: 'Snow.polygons', label: `John Snow's map and data on the 1854 London Cholera outbreak` },
    { id: 'Snow.pumps', label: `John Snow's map and data on the 1854 London Cholera outbreak` },
    { id: 'Snow.streets', label: `John Snow's map and data on the 1854 London Cholera outbreak` },
    { id: 'Wheat', label: `Playfair's Data on Wages and the Price of Wheat` },
    { id: 'Wheat.monarchs', label: `Playfair's Data on Wages and the Price of Wheat` },
    { id: 'Yeast', label: `Student's (1906) Yeast Cell Counts` },
    { id: 'YeastD.mat', label: `Student's (1906) Yeast Cell Counts` },
    { id: 'ZeaMays', label: `Darwin's Heights of Cross- and Self-fertilized Zea May Pairs` },
    { id: 'barley', label: `Yield data from a Minnesota barley trial` },
    { id: 'environmental', label: `Atmospheric environmental conditions in New York City` },
    { id: 'ethanol', label: `Engine exhaust fumes from burning ethanol` },
    { id: 'melanoma', label: `Melanoma skin cancer incidence` },
    { id: 'singer', label: `Heights of New York Choral Society singers` },
    { id: 'Aids2', label: `Australian AIDS Survival Data` },
    { id: 'Animals', label: `Brain and Body Weights for 28 Species` },
    { id: 'Boston', label: `Housing Values in Suburbs of Boston` },
    { id: 'Cars93', label: `Data from 93 Cars on Sale in the USA in 1993` },
    { id: 'Cushings', label: `Diagnostic Tests on Patients with Cushing's Syndrome` },
    { id: 'DDT', label: `DDT in Kale` },
    { id: 'GAGurine', label: `Level of GAG in Urine of Children` },
    { id: 'Insurance', label: `Numbers of Car Insurance claims` },
    { id: 'Melanoma', label: `Survival from Malignant Melanoma` },
    { id: 'OME', label: `Tests of Auditory Perception in Children with OME` },
    { id: 'Pima.te', label: `Diabetes in Pima Indian Women` },
    { id: 'Pima.tr', label: `Diabetes in Pima Indian Women` },
    { id: 'Pima.tr2', label: `Diabetes in Pima Indian Women` },
    { id: 'Rabbit', label: `Blood Pressure in Rabbits` },
    { id: 'Rubber', label: `Accelerated Testing of Tyre Rubber` },
    { id: 'SP500', label: `Returns of the Standard and Poors 500` },
    { id: 'Sitka', label: `Growth Curves for Sitka Spruce Trees in 1988` },
    { id: 'Sitka89', label: `Growth Curves for Sitka Spruce Trees in 1989` },
    { id: 'Skye', label: `AFM Compositions of Aphyric Skye Lavas` },
    { id: 'Traffic', label: `Effect of Swedish Speed Limits on Accidents` },
    { id: 'UScereal', label: `Nutritional and Marketing Information on US Cereals` },
    { id: 'UScrime', label: `The Effect of Punishment Regimes on Crime Rates` },
    { id: 'VA', label: `Veteran's Administration Lung Cancer Trial` },
    { id: 'abbey', label: `Determinations of Nickel Content` },
    { id: 'accdeaths', label: `Accidental Deaths in the US 1973-1978` },
    { id: 'anorexia', label: `Anorexia Data on Weight Change` },
    { id: 'bacteria', label: `Presence of Bacteria after Drug Treatments` },
    { id: 'beav1', label: `Body Temperature Series of Beaver 1` },
    { id: 'beav2', label: `Body Temperature Series of Beaver 2` },
    { id: 'biopsy', label: `Biopsy Data on Breast Cancer Patients` },
    { id: 'birthwt', label: `Risk Factors Associated with Low Infant Birth Weight` },
    { id: 'cabbages', label: `Data from a cabbage field trial` },
    { id: 'caith', label: `Colours of Eyes and Hair of People in Caithness` },
    { id: 'cats', label: `Anatomical Data from Domestic Cats` },
    { id: 'cement', label: `Heat Evolved by Setting Cements` },
    { id: 'chem', label: `Copper in Wholemeal Flour` },
    { id: 'coop', label: `Co-operative Trial in Analytical Chemistry` },
    { id: 'cpus', label: `Performance of Computer CPUs` },
    { id: 'crabs', label: `Morphological Measurements on Leptograpsus Crabs` },
    { id: 'deaths', label: `Monthly Deaths from Lung Diseases in the UK` },
    { id: 'drivers', label: `Deaths of Car Drivers in Great Britain 1969-84` },
    { id: 'eagles', label: `Foraging Ecology of Bald Eagles` },
    { id: 'epil', label: `Seizure Counts for Epileptics` },
    { id: 'farms', label: `Ecological Factors in Farm Management` },
    { id: 'fgl', label: `Measurements of Forensic Glass Fragments` },
    { id: 'forbes', label: `Forbes' Data on Boiling Points in the Alps` },
    { id: 'galaxies', label: `Velocities for 82 Galaxies` },
    { id: 'gehan', label: `Remission Times of Leukaemia Patients` },
    { id: 'genotype', label: `Rat Genotype Data` },
    { id: 'geyser', label: `Old Faithful Geyser Data` },
    { id: 'gilgais', label: `Line Transect of Soil in Gilgai Territory` },
    { id: 'hills', label: `Record Times in Scottish Hill Races` },
    { id: 'housing', label: `Frequency Table from a Copenhagen Housing Conditions Survey` },
    { id: 'immer', label: `Yields from a Barley Field Trial` },
    { id: 'leuk', label: `Survival Times and White Blood Counts for Leukaemia Patients` },
    { id: 'mammals', label: `Brain and Body Weights for 62 Species of Land Mammals` },
    { id: 'mcycle', label: `Data from a Simulated Motorcycle Accident` },
    { id: 'menarche', label: `Age of Menarche in Warsaw` },
    { id: 'michelson', label: `Michelson's Speed of Light Data` },
    { id: 'minn38', label: `Minnesota High School Graduates of 1938` },
    { id: 'motors', label: `Accelerated Life Testing of Motorettes` },
    { id: 'muscle', label: `Effect of Calcium Chloride on Muscle Contraction in Rat Hearts` },
    { id: 'newcomb', label: `Newcomb's Measurements of the Passage Time of Light` },
    { id: 'nlschools', label: `Eighth-Grade Pupils in the Netherlands` },
    { id: 'npk', label: `Classical N, P, K Factorial Experiment` },
    { id: 'npr1', label: `US Naval Petroleum Reserve No. 1 data` },
    { id: 'oats', label: `Data from an Oats Field Trial` },
    { id: 'painters', label: `The Painter's Data of de Piles` },
    { id: 'petrol', label: `N. L. Prater's Petrol Refinery Data` },
    { id: 'quine', label: `Absenteeism from School in Rural New South Wales` },
    { id: 'road', label: `Road Accident Deaths in US States` },
    { id: 'rotifer', label: `Numbers of Rotifers by Fluid Density` },
    { id: 'ships', label: `Ships Damage Data` },
    { id: 'shrimp', label: `Percentage of Shrimp in Shrimp Cocktail` },
    { id: 'shuttle', label: `Space Shuttle Autolander Problem` },
    { id: 'snails', label: `Snail Mortality Data` },
    { id: 'steam', label: `The Saturated Steam Pressure Data` },
    { id: 'stormer', label: `The Stormer Viscometer Data` },
    { id: 'survey', label: `Student Survey Data` },
    { id: 'synth.te', label: `Synthetic Classification Problem` },
    { id: 'synth.tr', label: `Synthetic Classification Problem` },
    { id: 'topo', label: `Spatial Topographic Data` },
    { id: 'waders', label: `Counts of Waders at 15 Sites in South Africa` },
    { id: 'whiteside', label: `House Insulation: Whiteside's Data` },
    { id: 'wtloss', label: `Weight Loss Data from an Obese Patient` },
    { id: 'Cigar', label: `Cigarette Consumption` },
    { id: 'Crime', label: `Crime in North Carolina` },
    { id: 'EmplUK', label: `Employment and Wages in the United Kingdom` },
    { id: 'Gasoline', label: `Gasoline Consumption` },
    { id: 'Grunfeld', label: `Grunfeld's Investment Data` },
    { id: 'Hedonic', label: `Hedonic Prices of Census Tracts in the Boston Area` },
    { id: 'LaborSupply', label: `Wages and Hours Worked` },
    { id: 'Males', label: `Wages and Education of Young Males` },
    { id: 'Produc', label: `US States Production` },
    { id: 'Snmesp', label: `Employment and Wages in Spain` },
    { id: 'SumHes', label: `The Penn World Table, v. 5` },
    { id: 'Wages', label: `Panel Data of Individual Wages` },
    { id: 'baseball', label: `Yearly batting records for all major league baseball players` },
    { id: 'AustralianElectionPolling', label: `Political opinion polls in Australia, 2004-07` },
    { id: 'AustralianElections', label: `elections to Australian House of Representatives, 1949-2007` },
    { id: 'EfronMorris', label: `Batting Averages for 18 major league baseball players, 1970` },
    { id: 'RockTheVote', label: `Voter turnout experiment, using Rock The Vote ads` },
    { id: 'UKHouseOfCommons', label: `1992 United Kingdom electoral returns` },
    { id: 'absentee', label: `Absentee and Machine Ballots in Pennsylvania State Senate Races` },
    { id: 'admit', label: `Applications to a Political Science PhD Program` },
    { id: 'bioChemists', label: `article production by graduate students in biochemistry Ph.D. programs` },
    { id: 'ca2006', label: `California Congressional Districts in 2006` },
    { id: 'iraqVote', label: `U.S. Senate vote on the use of force against Iraq, 2002.` },
    { id: 'politicalInformation', label: `Interviewer ratings of respondent levels of political information` },
    { id: 'presidentialElections', label: `elections for U.S. President, 1932-2012, by state` },
    { id: 'prussian', label: `Prussian army horse kick data` },
    { id: 'unionDensity', label: `cross national rates of trade union density` },
    { id: 'vote92', label: `Reports of voting in the 1992 U.S. Presidential election.` },
    { id: 'french_fries', label: `Sensory data from a french fries experiment.` },
    { id: 'smiths', label: `Demo data describing the Smiths.` },
    { id: 'tips', label: `Tipping data` },
    { id: 'car.test.frame', label: `Automobile Data from 'Consumer Reports' 1990` },
    { id: 'car90', label: `Automobile Data from 'Consumer Reports' 1990` },
    { id: 'cu.summary', label: `Automobile Data from 'Consumer Reports' 1990` },
    { id: 'kyphosis', label: `Data on Children who have had Corrective Spinal Surgery` },
    { id: 'solder', label: `Soldering of Components on Printed-Circuit Boards` },
    { id: 'stagec', label: `Stage C Prostate Cancer` },
    { id: 'PublicSchools', label: `US Expenditures for Public Schools` },
    { id: 'Bollen', label: `Bollen's Data on Industrialization and Political Democracy` },
    { id: 'CNES', label: `Variables from the 1997 Canadian National Election Study` },
    { id: 'Klein', label: `Klein's Data on the U. S. Economy` },
    { id: 'Kmenta', label: `Partly Artificial Data on the U. S. Economy` },
    { id: 'Tests', label: `Six Mental Tests` },
    { id: 'bladder', label: `Bladder Cancer Recurrences` },
    { id: 'cancer', label: `NCCTG Lung Cancer Data` },
    { id: 'cgd', label: `Chronic Granulotomous Disease data` },
    { id: 'colon', label: `Chemotherapy for Stage B/C colon cancer` },
    { id: 'flchain', label: `Assay of serum free light chain for 7874 subjects.` },
    { id: 'heart', label: `Stanford Heart Transplant data` },
    { id: 'kidney', label: `Kidney catheter data` },
    { id: 'leukemia', label: `Acute Myelogenous Leukemia survival data` },
    { id: 'logan', label: `Data from the 1972-78 GSS data used by Logan` },
    { id: 'lung', label: `NCCTG Lung Cancer Data` },
    { id: 'mgus', label: `Monoclonal gammapothy data` },
    { id: 'nwtco', label: `Data from the National Wilm's Tumor Study` },
    { id: 'ovarian', label: `Ovarian Cancer Survival Data` },
    { id: 'pbc', label: `Mayo Clinic Primary Biliary Cirrhosis Data` },
    { id: 'rats', label: `Rat treatment data from Mantel et al` },
    { id: 'stanford2', label: `More Stanford Heart Transplant data` },
    { id: 'tobin', label: `Tobin's Tobit data` },
    { id: 'veteran', label: `Veterans' Administration Lung Cancer study` },
    { id: 'Arthritis', label: `Arthritis Treatment Data` },
    { id: 'Baseball', label: `Baseball Data` },
    { id: 'BrokenMarriage', label: `Broken Marriage Data` },
    { id: 'Bundesliga', label: `Ergebnisse der Fussball-Bundesliga` },
    { id: 'Bundestag2005', label: `Votes in German Bundestag Election 2005` },
    { id: 'Butterfly', label: `Butterfly Species in Malaya` },
    { id: 'CoalMiners', label: `Breathlessness and Wheeze in Coal Miners` },
    { id: 'DanishWelfare', label: `Danish Welfare Study Data` },
    { id: 'Employment', label: `Employment Status` },
    { id: 'Federalist', label: `'May' in Federalist Papers` },
    { id: 'Hitters', label: `Hitters Data` },
    { id: 'HorseKicks', label: `Death by Horse Kicks` },
    { id: 'Hospital', label: `Hospital data` },
    { id: 'JobSatisfaction', label: `Job Satisfaction Data` },
    { id: 'JointSports', label: `Opinions About Joint Sports` },
    { id: 'Lifeboats', label: `Lifeboats on the Titanic` },
    { id: 'NonResponse', label: `Non-Response Survey Data` },
    { id: 'OvaryCancer', label: `Ovary Cancer Data` },
    { id: 'PreSex', label: `Pre-marital Sex and Divorce` },
    { id: 'Punishment', label: `Corporal Punishment Data` },
    { id: 'RepVict', label: `Repeat Victimization Data` },
    { id: 'Saxony', label: `Families in Saxony` },
    { id: 'SexualFun', label: `Sex is Fun` },
    { id: 'SpaceShuttle', label: `Space Shuttle O-ring Failures` },
    { id: 'Suicide', label: `Suicide Rates in Germany` },
    { id: 'Trucks', label: `Truck Accidents Data` },
    { id: 'UKSoccer', label: `UK Soccer Scores` },
    { id: 'VisualAcuity', label: `Visual Acuity in Left and Right Eyes` },
    { id: 'VonBort', label: `Von Bortkiewicz Horse Kicks Data` },
    { id: 'WeldonDice', label: `Weldon's Dice Data` },
    { id: 'WomenQueue', label: `Women in Queues` },
    { id: 'MatchIt.url', label: `Table of links for Zelig` },
    { id: 'PErisk', label: `Political Economic Risk Data from 62 Countries in 1987` },
    { id: 'SupremeCourt', label: `U.S. Supreme Court Vote Matrix` },
    { id: 'Weimar', label: `1932 Weimar election data` },
    { id: 'Zelig.url', label: `Table of links for Zelig` },
    { id: 'approval', label: `U.S. Presidential Approval Data` },
    { id: 'bivariate', label: `Sample data for bivariate probit regression` },
    { id: 'coalition', label: `Coalition Dissolution in Parliamentary Democracies` },
    { id: 'coalition2', label: `Coalition Dissolution in Parliamentary Democracies, Modified Version` },
    { id: 'eidat', label: `Simulation Data for Ecological Inference` },
    { id: 'free1', label: `Freedom of Speech Data` },
    { id: 'free2', label: `Freedom of Speech Data` },
    { id: 'friendship', label: `Simulated Example of Schoolchildren Friendship Network` },
    { id: 'grunfeld', label: `Simulation Data for model Seemingly Unrelated Regression (sur) that corresponds to method SUR of systemfit` },
    { id: 'hoff', label: `Social Security Expenditure Data` },
    { id: 'homerun', label: `Sample Data on Home Runs Hit By Mark McGwire and Sammy Sosa in 1998.` },
    { id: 'immi1', label: `Individual Preferences Over Immigration Policy` },
    { id: 'immi2', label: `Individual Preferences Over Immigration Policy` },
    { id: 'immi3', label: `Individual Preferences Over Immigration Policy` },
    { id: 'immi4', label: `Individual Preferences Over Immigration Policy` },
    { id: 'immi5', label: `Individual Preferences Over Immigration Policy` },
    { id: 'immigration', label: `Individual Preferences Over Immigration Policy` },
    { id: 'klein', label: `Simulation Data for model Two-Stage Least Square (twosls) that corresponds to method 2SLS of systemfit` },
    { id: 'kmenta', label: `Simulation Data for model Three-Stage Least Square (threesls) that corresponds to method 3SLS of systemfit` },
    { id: 'macro', label: `Macroeconomic Data` },
    { id: 'mexico', label: `Voting Data from the 1988 Mexican Presidental Election` },
    { id: 'mid', label: `Militarized Interstate Disputes` },
    { id: 'newpainters', label: `The Discretized Painter's Data of de Piles` },
    { id: 'sanction', label: `Multilateral Economic Sanctions` },
    { id: 'sna.ex', label: `Simulated Example of Social Network Data` },
    { id: 'swiss', label: `Swiss Fertility and Socioeconomic Indicators (1888) Data` },
    { id: 'tobin', label: `Tobin's Tobit Data` },
    { id: 'turnout', label: `Turnout Data Set from the National Election Survey` },
    { id: 'voteincome', label: `Sample Turnout and Demographic Data from the 2000 Current Population Survey` },
    { id: 'BCG', label: `BCG Vaccine Data` },
    { id: 'BtheB', label: `Beat the Blues Data` },
    { id: 'CYGOB1', label: `CYG OB1 Star Cluster Data` },
    { id: 'Forbes2000', label: `The Forbes 2000 Ranking of the World's Biggest Companies (Year 2004)` },
    { id: 'GHQ', label: `General Health Questionnaire` },
    { id: 'Lanza', label: `Prevention of Gastointestinal Damages` },
    { id: 'agefat', label: `Total Body Composision Data` },
    { id: 'aspirin', label: `Aspirin Data` },
    { id: 'birthdeathrates', label: `Birth and Death Rates Data` },
    { id: 'bladdercancer', label: `Bladder Cancer Data` },
    { id: 'clouds', label: `Cloud Seeding Data` },
    { id: 'epilepsy', label: `Epilepsy Data` },
    { id: 'foster', label: `Foster Feeding Experiment` },
    { id: 'heptathlon', label: `Olympic Heptathlon Seoul 1988` },
    { id: 'mastectomy', label: `Survival Times after Mastectomy of Breast Cancer Patients` },
    { id: 'meteo', label: `Meteorological Measurements for 11 Years` },
    { id: 'orallesions', label: `Oral Lesions in Rural India` },
    { id: 'phosphate', label: `Phosphate Level Data` },
    { id: 'pistonrings', label: `Piston Rings Failures` },
    { id: 'planets', label: `Exoplanets Data` },
    { id: 'plasma', label: `Blood Screening Data` },
    { id: 'polyps', label: `Familial Andenomatous Polyposis` },
    { id: 'polyps3', label: `Familial Andenomatous Polyposis` },
    { id: 'pottery', label: `Romano-British Pottery Data` },
    { id: 'rearrests', label: `Rearrests of Juvenile Felons` },
    { id: 'respiratory', label: `Respiratory Illness Data` },
    { id: 'roomwidth', label: `Students Estimates of Lecture Room Width` },
    { id: 'schizophrenia', label: `Age of Onset of Schizophrenia Data` },
    { id: 'schizophrenia2', label: `Schizophrenia Data` },
    { id: 'schooldays', label: `Days not Spent at School` },
    { id: 'skulls', label: `Egyptian Skulls` },
    { id: 'smoking', label: `Nicotine Gum and Smoking Cessation` },
    { id: 'students', label: `Student Risk Taking` },
    { id: 'suicides', label: `Crowd Baiting Behaviour and Suicides` },
    { id: 'toothpaste', label: `Toothpaste Data` },
    { id: 'voting', label: `House of Representatives Voting Data` },
    { id: 'water', label: `Mortality and Water Hardness` },
    { id: 'watervoles', label: `Water Voles Data` },
    { id: 'waves', label: `Electricity from Wave Power at Sea` },
    { id: 'weightgain', label: `Gain in Weight of Rats` },
    { id: 'womensrole', label: `Womens Role in Society` },
    { id: 'Bechtoldt', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Bechtoldt.1', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Bechtoldt.2', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Dwyer', label: `8 cognitive variables used by Dwyer for an example.` },
    { id: 'Gleser', label: `Example data from Gleser, Cronbach and Rajaratnam (1965) to show basic principles of generalizability theory.` },
    { id: 'Gorsuch', label: `Example data set from Gorsuch (1997) for an example factor extension.` },
    { id: 'Harman.5', label: `5 socio-economic variables from Harman (1967)` },
    { id: 'Harman.8', label: `Correlations of eight physical variables (from Harman, 1966)` },
    { id: 'Harman.political', label: `Eight political variables used by Harman (1967) as example 8.17` },
    { id: 'Holzinger', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Holzinger.9', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Reise', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Schmid', label: `12 variables created by Schmid and Leiman to show the Schmid-Leiman Transformation` },
    { id: 'Thurstone', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Thurstone.33', label: `Seven data sets showing a bifactor solution.` },
    { id: 'Tucker', label: `9 Cognitive variables discussed by Tucker and Lewis (1973)` },
    { id: 'ability', label: `16 ability items scored as correct or incorrect.` },
    { id: 'affect', label: `Two data sets of affect and arousal scores as a function of personality and movie conditions` },
    { id: 'bfi', label: `25 Personality items representing 5 factors` },
    { id: 'bfi.dictionary', label: `25 Personality items representing 5 factors` },
    { id: 'blot', label: `Bond's Logical Operations Test - BLOT` },
    { id: 'burt', label: `11 emotional variables from Burt (1915)` },
    { id: 'cities', label: `Distances between 11 US cities` },
    { id: 'cubits', label: `Galton's example of the relationship between height and 'cubit' or forearm length` },
    { id: 'cushny', label: `A data set from Cushny and Peebles (1905) on the effect of three drugs on hours of sleep, used by Student (1908)` },
    { id: 'epi', label: `Eysenck Personality Inventory (EPI) data for 3570 participants` },
    { id: 'epi.bfi', label: `13 personality scales from the Eysenck Personality Inventory and Big 5 inventory` },
    { id: 'epi.dictionary', label: `Eysenck Personality Inventory (EPI) data for 3570 participants` },
    { id: 'galton', label: `Galton's Mid parent child height data` },
    { id: 'heights', label: `A data.frame of the Galton (1888) height and cubit data set.` },
    { id: 'income', label: `US family income from US census 2008` },
    { id: 'iqitems', label: `16 multiple choice IQ items` },
    { id: 'msq', label: `75 mood items from the Motivational State Questionnaire for 3896 participants` },
    { id: 'neo', label: `NEO correlation matrix from the NEO_PI_R manual` },
    { id: 'peas', label: `Galton's Peas` },
    { id: 'sat.act', label: `3 Measures of ability: SATV, SATQ, ACT` },
    { id: 'withinBetween', label: `An example of the distinction between within group and between group correlations` },
    { id: 'Bosco', label: `Boscovich Data` },
    { id: 'CobarOre', label: `Cobar Ore data` },
    { id: 'Mammals', label: `Garland(1983) Data on Running Speed of Mammals` },
    { id: 'barro', label: `Barro Data` },
    { id: 'engel', label: `Engel Data` },
    { id: 'uis', label: `UIS Drug Treatment study data` },
    { id: 'dietox', label: `Growth curves of pigs in a 3x3 factorial experiment` },
    { id: 'koch', label: `Ordinal Data from Koch` },
    { id: 'ohio', label: `Ohio Children Wheeze Status` },
    { id: 'respdis', label: `Clustered Ordinal Respiratory Disorder` },
    { id: 'respiratory', label: `Data from a clinical trial comparing two treatments for a respiratory illness` },
    { id: 'seizure', label: `Epiliptic Seizures` },
    { id: 'sitka89', label: `Growth of Sitka Spruce Trees` },
    { id: 'spruce', label: `Log-size of 79 Sitka spruce trees` },
    { id: 'liver', label: `Liver related laboratory data` },
    { id: 'portpirie', label: `Rain, wavesurge and portpirie datasets.` },
    { id: 'rain', label: `Rain, wavesurge and portpirie datasets.` },
    { id: 'summer', label: `Air pollution data, separately for summer and winter months` },
    { id: 'wavesurge', label: `Rain, wavesurge and portpirie datasets.` },
    { id: 'winter', label: `Air pollution data, separately for summer and winter months` },
    { id: 'arthritis', label: `Rheumatoid Arthritis Clinical Trial` },
    { id: 'housing', label: `Homeless Data` },
    { id: 'bmw', label: `Daily Log Returns on BMW Share Price` },
    { id: 'danish', label: `Danish Fire Insurance Claims` },
    { id: 'nidd.annual', label: `The River Nidd Data` },
    { id: 'nidd.thresh', label: `The River Nidd Data` },
    { id: 'siemens', label: `Daily Log Returns on Siemens Share Price` },
    { id: 'sp.raw', label: `SP Data to June 1993` },
    { id: 'spto87', label: `SP Return Data to October 1987` },
    { id: 'Dyestuff', label: `Yield of dyestuff by batch` },
    { id: 'Dyestuff2', label: `Yield of dyestuff by batch` },
    { id: 'InstEval', label: `University Lecture/Instructor Evaluations by Students at ETH` },
    { id: 'Pastes', label: `Paste strength by batch and cask` },
    { id: 'Penicillin', label: `Variation in penicillin testing` },
    { id: 'VerbAgg', label: `Verbal Aggression item responses` },
    { id: 'cake', label: `Breakage Angle of Chocolate Cakes` },
    { id: 'cbpp', label: `Contagious bovine pleuropneumonia` },
    { id: 'grouseticks', label: `Data on red grouse ticks from Elston et al. 2001` },
    { id: 'sleepstudy', label: `Reaction times in a sleep deprivation study` },
];
